# Configuración mínima para desarrollo
controller:
  replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabledMechanisms: ""

persistence:
  enabled: false

metrics:
  jmx:
    enabled: false
  serviceMonitor:
    enabled: false
