# Configuración para el cluster Kafka Warehouse
controller:
  replicaCount: 1

# Usar la misma configuración de listeners que el Kafka principal
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabledMechanisms: ""

persistence:
  enabled: false

metrics:
  jmx:
    enabled: false
  serviceMonitor:
    enabled: false

# Configuración específica para cluster warehouse
extraConfig: |
  auto.create.topics.enable=true
  default.replication.factor=1
  min.insync.replicas=1
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  transaction.state.log.min.isr=1

# Recursos optimizados para el cluster warehouse
resources:
  limits:
    memory: 1Gi
    cpu: 500m
  requests:
    memory: 512Mi
    cpu: 200m

# Configuración de nombre para evitar conflictos con el Kafka principal
nameOverride: "kafka-warehouse"
fullnameOverride: "kafka-warehouse"

# Labels para identificación
commonLabels:
  app.kubernetes.io/instance: kafka-warehouse
  app.kubernetes.io/component: kafka-warehouse

# Configuración de servicios específica
service:
  type: ClusterIP