# Configuración para desarrollo y testing
# Usar con: helm upgrade --install mqtt-event-generator ./mqtt-event-generator -f values-dev.yaml

# Configuración MQTT para desarrollo
mqtt:
  # Usar FQDN completo para mayor confiabilidad
  broker: "tcp://emqx.medisupply.svc.cluster.local:1883"
  clientId: "event-generator-dev"
  topic: "events/sensor/dev"
  username: "admin"
  password: "public"

# Eventos más frecuentes para desarrollo
eventGenerator:
  intervalSeconds: 10

# Recursos mínimos para desarrollo
resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi

# Habilitar logs más detallados
podAnnotations:
  sidecar.istio.io/inject: "true"
  # Opcional: agregar anotaciones para debugging
  kubectl.kubernetes.io/default-container: mqtt-event-generator