{{- if .Values.jaeger.enabled }}
# Telemetry configuration for distributed tracing
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tracing
  namespace: {{ .Values.global.medisupplyNamespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  tracing:
  - providers:
    - name: {{ .Values.jaeger.provider.name }}
  - customTags:
      service.name:
        header:
          name: "{{ .Values.jaeger.customTags.serviceName.header }}"
      service.version:
        header:
          name: "{{ .Values.jaeger.customTags.serviceVersion.header }}"
      request.id:
        header:
          name: "{{ .Values.jaeger.customTags.requestId.header }}"
---
# Jaeger configuration via ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-jaeger-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
data:
  mesh: |
    extensionProviders:
    - name: {{ .Values.jaeger.provider.name }}
      envoyOtelAls:
        service: {{ .Values.jaeger.provider.service }}
        port: {{ .Values.jaeger.provider.port }}
    defaultProviders:
      tracing:
      - {{ .Values.jaeger.provider.name }}
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  tracing:
  - providers:
    - name: {{ .Values.jaeger.provider.name }}
{{- end }}