# Default values for observability chart
global:
  namespace: istio-system
  medisupplyNamespace: medisupply

# Grafana Dashboard Configuration
grafana:
  enabled: true
  dashboard:
    name: medisupply-dashboard
    title: "MediSupply Services Dashboard"
    tags: ["medisupply", "microservices"]
    style: "dark"
    timezone: "browser"
    refresh: "5s"
    timeRange:
      from: "now-1h"
      to: "now"

# Prometheus Configuration
prometheus:
  enabled: true
  config:
    scrapeInterval: 15s
    services:
      - name: product-service
        metricsPath: /metrics
        port: http
        interval: 30s
      - name: purchase-plan-service
        metricsPath: /metrics
        port: http
        interval: 30s

# ServiceMonitor (requires Prometheus Operator)
serviceMonitor:
  enabled: false
  interval: 30s
  path: /metrics
  port: http

# Jaeger Tracing Configuration
jaeger:
  enabled: true
  provider:
    name: jaeger
    service: jaeger-collector.istio-system.svc.cluster.local
    port: 14250
  customTags:
    serviceName:
      header: "service-name"
    serviceVersion:
      header: "service-version"
    requestId:
      header: "x-request-id"

# Kiali Configuration
kiali:
  enabled: true
  version: v1.76.0
  image: quay.io/kiali/kiali
  auth:
    strategy: anonymous
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 64Mi
  externalServices:
    grafana:
      enabled: true
      inClusterUrl: 'http://grafana.istio-system:3000'
      url: 'http://localhost:3000'
    prometheus:
      url: "http://prometheus.istio-system:9090"
    tracing:
      enabled: true
      inClusterUrl: 'http://tracing.istio-system/jaeger'
      externalUrl: "http://localhost:16686"